In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests

# Dependencies and Setup
import requests
import gmaps
import os

# Import API key
from config import g_key
# Import the API key.
from config import g_key

In [2]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,Punta Arenas,-53.15,-70.92,46.40,70,75,20.80,CL,2020-10-30 05:17:50
1,1,Mackay,-21.15,149.20,88.00,55,0,19.46,AU,2020-10-30 05:15:52
2,2,Busselton,-33.65,115.33,89.01,20,0,4.34,AU,2020-10-30 05:17:50
3,3,Atuona,-9.80,-139.03,78.22,68,60,15.03,PF,2020-10-30 05:17:50
4,4,Hilo,19.73,-155.09,78.80,83,90,1.92,US,2020-10-30 05:17:50

In [3]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [4]:
city_data_df.sort_values(["Max Temp"], ascending = [False])

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
167,167,Blackwater,-23.58,148.88,93.87,13,0,12.33,AU,2020-10-30 05:18:40
500,500,Bowen,-20.02,148.23,93.20,24,0,17.22,AU,2020-10-30 05:20:16
560,560,Bintulu,3.17,113.03,91.40,66,20,8.05,MY,2020-10-30 05:20:35
101,101,Geraldton,-28.77,114.60,91.40,29,0,13.87,AU,2020-10-30 05:18:16
481,481,Pringsewu,-5.36,104.97,91.18,49,46,3.94,ID,2020-10-30 05:20:11
...,...,...,...,...,...,...,...,...,...,...
31,31,Saskylakh,71.92,114.08,0.39,85,18,6.69,RU,2020-10-30 05:17:58
68,68,Khatanga,71.97,102.50,-0.76,85,0,9.26,RU,2020-10-30 05:18:07
394,394,Aykhal,66.00,111.50,-1.32,91,81,2.35,RU,2020-10-30 05:19:46
36,36,Udachnyy,66.42,112.40,-3.33,90,80,1.32,RU,2020-10-30 05:17:59
352,352,Chokurdakh,70.63,147.92,-4.97,93,98,0.67,RU,2020-10-30 05:19:34

In [5]:
city_data_df.dtypes

City_ID         int64
City           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
Country        object
Date           object
dtype: object

In [6]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [7]:
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))

In [8]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=temps)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [9]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"].astype(float)
# Assign the figure variable.
fig = gmaps.figure()
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp])
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [10]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp], dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [11]:
# Heatmap of Cloudiness 
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
clouds = city_data_df["Cloudiness"]
# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights= clouds, dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [12]:
# Heatmap of Windspeed
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
wind = city_data_df["Wind Speed"]
# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights= wind, dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [13]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [14]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
1,1,Mackay,-21.15,149.20,88.00,55,0,19.46,AU,2020-10-30 05:15:52
2,2,Busselton,-33.65,115.33,89.01,20,0,4.34,AU,2020-10-30 05:17:50
3,3,Atuona,-9.80,-139.03,78.22,68,60,15.03,PF,2020-10-30 05:17:50
4,4,Hilo,19.73,-155.09,78.80,83,90,1.92,US,2020-10-30 05:17:50
11,11,Rikitea,-23.12,-134.97,75.45,73,100,4.23,PF,2020-10-30 05:17:53
12,12,Pauini,-7.71,-66.98,77.34,81,99,2.01,BR,2020-10-30 05:17:53
13,13,Sao Jose Da Coroa Grande,-8.90,-35.15,76.53,86,51,11.72,BR,2020-10-30 05:17:53
15,15,Werda,-25.27,23.28,76.60,36,98,14.45,BW,2020-10-30 05:17:54
18,18,Mahebourg,-20.41,57.70,75.00,49,13,8.99,MU,2020-10-30 05:15:21
21,21,Butaritari,3.07,172.79,82.24,76,31,11.77,KI,2020-10-30 05:15:44

In [15]:
preferred_cities_df.count()

City_ID       161
City          161
Lat           161
Lng           161
Max Temp      161
Humidity      161
Cloudiness    161
Wind Speed    161
Country       161
Date          161
dtype: int64

In [16]:
preferred_cities_df.notnull().sum()

City_ID       161
City          161
Lat           161
Lng           161
Max Temp      161
Humidity      161
Cloudiness    161
Wind Speed    161
Country       161
Date          161
dtype: int64

In [17]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

                        City Country  Max Temp    Lat     Lng Hotel Name
1                     Mackay      AU     88.00 -21.15  149.20
2                  Busselton      AU     89.01 -33.65  115.33
3                     Atuona      PF     78.22  -9.80 -139.03
4                       Hilo      US     78.80  19.73 -155.09
11                   Rikitea      PF     75.45 -23.12 -134.97
12                    Pauini      BR     77.34  -7.71  -66.98
13  Sao Jose Da Coroa Grande      BR     76.53  -8.90  -35.15
15                     Werda      BW     76.60 -25.27   23.28
18                 Mahebourg      MU     75.00 -20.41   57.70
21                Butaritari      KI     82.24   3.07  172.79

In [18]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]


    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    
   
    # Grab the first hotel from the results and store the name. 
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]    
    except (KeyError, IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [22]:
hotel_df.head(10)

,City,Country,Max Temp,Lat,Lng,Hotel Name
1,Mackay,AU,88.00,-21.15,149.20,International Lodge Motel
2,Busselton,AU,89.01,-33.65,115.33,Observatory Guest House
3,Atuona,PF,78.22,-9.80,-139.03,Villa Enata
4,Hilo,US,78.80,19.73,-155.09,Hilo Hawaiian Hotel
11,Rikitea,PF,75.45,-23.12,-134.97,Pension Maro'i
12,Pauini,BR,77.34,-7.71,-66.98,Casa do Kiwliks
13,Sao Jose Da Coroa Grande,BR,76.53,-8.90,-35.15,Crôa Mares Hotel
15,Werda,BW,76.60,-25.27,23.28,
18,Mahebourg,MU,75.00,-20.41,57.70,Shandrani Beachcomber Resort & Spa
21,Butaritari,KI,82.24,3.07,172.79,Isles Sunset Lodge

In [23]:
# Add a heatmap of temperature for the vacation spots.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [24]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [25]:
info_box_template = """
<dl>
<dt>Name</dt><dd>{column1}</dd>
<dt>Another name</dt><dd>{column2}</dd>
</dl>
"""

In [27]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [28]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))